# Generated by Django 2.2.7 on 2020-07-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
            preserve_default=False,
        ),
    ]
