# Generated by Django 2.2.7 on 2020-07-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentlist_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
